### ISSUE TITLE
Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime 

### ISSUE THREAD

**Issue by jeer65** [PredixDev/predix-webapp-starter#25]
I'm not able to run this predix-webapp-starter, my OS is windows 10 from a GE laptop, but once I installed all dependencies, I found the below error:

E:\GE\Predix\predix\predixDev\predix-webapp>gulp
[23:11:34] Using gulpfile E:\GE\Predix\predix\predixDev\predix-webapp\gulpfile.js
[23:11:34] Starting 'default'...
[23:11:34] Starting 'compile:sass'...
[23:11:34] 'compile:sass' errored after 15 ms
[23:11:34] Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (57)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v3.13.1
    at module.exports (E:\GE\Predix\predix\predixDev\predix-webapp\node_modules\node-sass\lib\binding.js:13:13)
    at Object.<anonymous> (E:\GE\Predix\predix\predixDev\predix-webapp\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (E:\GE\Predix\predix\predixDev\predix-webapp\node_modules\gulp-sass\index.js:187:21)

Any suggestion?,

**Comment by cleret** [comment]
Hi, this is a compiler error. I encountered it few times. One way to resolve it, is to install Microsoft Visual Studio.

**Comment by gstroup** [comment]
Yes, installing Visual Studio should fix it.  Another option I've heard about might be to install the "windows-build-tools" package from npm.

`npm install --global --production windows-build-tools`

**Comment by jeer65** [comment]
I have installed Visual Studio 2017, version 15.5.2. Also I tried with you command 
npm install --global --production windows-build-tools
and it doesn't work unfortunately for me, I tried in another computer with windows 64 same issue, but I run the app in a linux box (CentOS) no issues, but all my tools are running on windows, so I was wondering what library is blocking me to run this web-app, Have you tried to run this app in Windows 10 64?
Thank you in advance

**Comment by turnerth** [comment]
Some suggestions here...
https://github.com/sass/node-sass/issues/1764

Let us know how it goes.

**Comment by jeer65** [comment]
@turnerth  Thank you so much for the link but that link is for MacOS system, but I ran the command anyways and still is not working same issue.
 I tried to look on the website for this issue for windows 64 bit I found an possible fix 
 ( [https://github.com/Microsoft/PartsUnlimited/issues/134](https://github.com/Microsoft/PartsUnlimited/issues/134 ))
but it didn't work

**Comment by mdwragg** [comment]
I may be way off but have you tried rebuilding native extensions on Node 9? Guessing the instructions in that thread pre-date Node v9.
